# Generated by Django 5.0.14 on 2026-08-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_approved_by_remove_order_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement_reference',
            field=models.CharField(blank=True, help_text='Reference from Settlement', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference from Payment Service', max_length=100, null=True),
        ),
    ]
