# Generated by Django 5.0.14 on 2026-08-17 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_settlement_reference_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_order_qty', models.PositiveIntegerField(default=1)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'org_type__in': ['VENDOR', 'BOTH']}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
