# Generated by Django 5.0.14 on 2026-08-13 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROCUREMENT_OFFICER', 'Procurement Officer'), ('MANAGER', 'Manager'), ('CFO', 'Chief Financial Officer'), ('ADMIN', 'Organization Admin')], default='PROCUREMENT_OFFICER', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='spending_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
