# Generated by Django 5.0.14 on 2026-08-14 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded')], default='DRAFT', max_length=20)),
                ('closing_date', models.DateTimeField()),
                ('buyer_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='organizations.organization')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submitted_bids', to=settings.AUTH_USER_MODEL)),
                ('vendor_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to='organizations.organization')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rfqs.rfq')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
